name: basic_utils
description: Common util classes providing a solution for different situations.
version: 3.0.0-nullsafety.0
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.13.0
  logging: ^1.0.0
  json_annotation: ^4.0.0
  pointycastle: ^3.0.0-nullsafety.2
  convert: ^3.0.0
  crypto: ^3.0.0


dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.1
  pedantic: ^1.10.0
  test: ^1.16.3